site_name: Checcasino

site_url: https://mydomain.org/mysite
theme:
  palette:
    primary: purple
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate 
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - tags:
      tags_file: tags.md
  - blog

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Code Docs: 
    - Java: coding/my-first-java-file.md
  - About:
      - About me: about/about.md
      - Childhood: about/childhood.md
  - Tags: tags.md
  - Blog: 
    - blog/index.md